# default update interval
interval: 432100
fda:
  # maximum collections to index
  collections: 1000
generators:
  # special generator for joining "date:publisher,place"
  publisher:
    paste:
    - field: place
      default: ""
    - ":"
    - name
    - ","
    - field: date
      default: ""
templates:
  traditional:
    creator: dc.contributor.author
    title: dc.title
    date: dc.date.issued
    description: dc.description
    format: dc.format
    citation: dc.identifier.citation
    relation: dc.identifier.citation
    available: dc.identifier.uri
    identifier:
      # concatenate all field value lists
      - dc.identifier.uri
      - dc.identifier.citation
    publisher: dc.publisher
    rights: dc.rights
    subject: dc.subject
    type: dc.type
  viewer:
    available: ss_handle
    creator: sm_author
    data_provider:
      string: "NYU"
    date:
      date:
        format: "%B %Y"
        value: ss_publication_date_text
    description:
      paste:
        - sm_collection_label
        - paste:
          - string: " "
          - sm_field_volume
          default: ""
        - string: ", ("
        - field: ss_publication_date_text
          default: ""
        - string: ")"
    identifier: ss_handle
    language: sm_language_code
    publisher: sm_publisher
    series: sm_field_volume
    subject: sm_subject_label
    title: ss_title
    type:
      string: "Journal"
  dlib:
    identifier: identifier
    title: entity_title
    available: handle
    citation: handle
    date: publication_date
    description: description
    subject: subject
    creator: editor
    language: language
collections:
  # key is unique collection identifier
  vinopal:
    source: FDA
    hdl: 27729
    template: traditional
  april:
    source: FDA
    hdl: 34767
    template: traditional
  kate:
    source: FDA
    hdl: 34600
    template: traditional
  ngo:
    source: FDA
    hdl: 33605
    template: traditional
    fields:
      publisher:
        # use custom generator, defined above
        publisher:
          place: dc.publisher.place
          name: dc.publisher
          date: dc.date.issued
      type:
        # fixed value
        string: "Report"
  freedom:
    source: DLTS
    core: viewer
    code: fdm
    template: viewer
  theliberator:
    source: DLTS
    core: viewer
    code: theliberator
    template: viewer
  rosie:
    source: DLib
    path: "rosie/content.json"
    name: "The Real Rosie the Riveter Project"
    template: dlib
    fields:
      type:
        string: "Video"
      format:
        string: "Video"
  masses:
    source: DLib
    path: "themasses/books.json"
    name: "The Masses"
    template: dlib
    fields:
      title:
        paste:
          - entity_title
          - string: ' '
          - field: description
            default: ''
      type:
        string: "Book"
      format:
        string: "Book"
