# default update interval
interval: 432100
fda:
  # maximum collections to index
  collections: 1000
generators:
  # special generator for joining "date:publisher,place"
  publisher:
    paste:
    - field: place
      default: ""
    - ":"
    - name
    - ","
    - field: date
      default: ""
templates:
  traditional:
    creator: dc.contributor.author
    title: dc.title
    date: dc.date.issued
    description: dc.description
    format: dc.format
    citation: dc.identifier.citation
    relation: dc.identifier.citation
    available: dc.identifier.uri
    identifier:
      # concatenate all field value lists
      - dc.identifier.uri
      - dc.identifier.citation
    publisher: dc.publisher
    rights: dc.rights
    subject: dc.subject
    type: dc.type
collections:
  # key is unique collection identifier
  vinopal:
    source: FDA
    hdl: 27729
    template: traditional
  april:
    source: FDA
    hdl: 34767
    template: traditional
  kate:
    source: FDA
    hdl: 34600
    template: traditional
  ngo:
    source: FDA
    hdl: 33605
    template: traditional
    fields:
      publisher:
        # use custom generator, defined above
        publisher:
          place: dc.publisher.place
          name: dc.publisher
          date: dc.date.issued
      type:
        # fixed value
        string: "Report"
