# default update interval
interval: 86400
cache: /tmp/primo-endpoint.cache
generators:
  # special generator for joining "date:publisher,place"
  publisher:
    paste:
    - field: place
      default: ""
    - ":"
    - name
    - ","
    - field: date
      default: ""
templates:
  traditional:
    creator: dc.contributor.author
    title: dc.title
    date: dc.date.issued
    description: dc.description
    format: dc.format
    citation: dc.identifier.citation
    relation: dc.identifier.citation
    available: dc.identifier.uri
    identifier:
      # concatenate all field value lists
      - dc.identifier.uri
      - dc.identifier.citation
    publisher: dc.publisher
    rights: dc.rights
    subject: dc.subject
    type: dc.type
  ngo:
    creator: dc.contributor.author
    date: dc.date.issued
    description: dc.description
    format: dc.format
    citation: dc.identifier.citation
    relation: dc.identifier.citation
    available: dc.identifier.uri
    identifier:
      # concatenate all field value lists
      - dc.identifier.uri
      - dc.identifier.citation
    publisher:
      # use custom generator, defined above
      publisher:
        place: dc.publisher.place
        name: dc.publisher
        date: dc.date.issued
    rights: dc.rights
    subject: dc.subject
    title: dc.title
    type:
      # fixed value
      string: "Report"
collections:
  # key is unique collection identifier
  vinopal: 
    source: FDA
    id:  520  
    template: traditional 
  april: 
    source: FDA
    id:  683  
    template: traditional 
  kate: 
    source: FDA
    id:  677  
    template: traditional 
  ngo:
    source: FDA
    id: 631
    template: ngo 
